const styles: Record<string, any> = {
  container: {
    minHeight: "100vh",
    width: "100vw",
    overflowX: "hidden",
    backgroundColor: "white",
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
  },
  headerBar: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 50,
    padding: "16px",
    paddingTop: "16px",
  },
  headerContainer: {
    maxWidth: "1280px",
    margin: "0 auto",
  },
  navbar: {
    background: "rgba(255, 255, 255, 0.1)",
    backdropFilter: "blur(24px)",
    border: "1px solid rgba(255, 255, 255, 0.2)",
    borderRadius: "24px",
    boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.25)",
    padding: "16px 24px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  logo: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    textDecoration: "none",
    color: "black",
  },
  logoIcon: {
    width: "32px",
    height: "32px",
    background: "linear-gradient(135deg, #50bc72, #41599c)",
    borderRadius: "8px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "white",
    fontWeight: "bold",
    fontSize: "18px",
  },
  logoText: {
    fontSize: "24px",
    fontWeight: "bold",
    color: "black",
  },
  nav: {
    display: "flex",
    gap: "32px",
  },
  navLink: {
    color: "#6b7280",
    textDecoration: "none",
    transition: "color 0.3s",
    cursor: "pointer",
  },
  backButton: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 16px",
    backgroundColor: "transparent",
    border: "none",
    borderRadius: "8px",
    color: "black",
    cursor: "pointer",
    transition: "background-color 0.3s",
  },
  section: {
    paddingTop: "128px",
    paddingBottom: "80px",
    padding: "128px 16px 80px",
    position: "relative",
    overflow: "hidden",
  },
  backgroundCircle1: {
    position: "absolute",
    top: "-160px",
    right: "-160px",
    width: "320px",
    height: "320px",
    borderRadius: "50%",
    opacity: 0.05,
    background: "linear-gradient(135deg, #50bc72, #41599c)",
    animation: "pulse 2s infinite",
  },
  backgroundCircle2: {
    position: "absolute",
    bottom: "-160px",
    left: "-160px",
    width: "384px",
    height: "384px",
    borderRadius: "50%",
    opacity: 0.03,
    background: "linear-gradient(135deg, #50bc72, #41599c)",
    animation: "pulse 2s infinite",
    animationDelay: "1s",
  },
  formContainer: {
    maxWidth: "448px",
    margin: "0 auto",
    position: "relative",
    zIndex: 10,
  },
  header: {
    textAlign: "center",
    marginBottom: "32px",
  },
  title: {
    fontSize: "30px",
    fontWeight: "bold",
    color: "black",
    marginBottom: "8px",
  },
  subtitle: {
    color: "#6b7280",
  },
  card: {
    backgroundColor: "white",
    borderRadius: "12px",
    boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.25)",
    border: "none",
    overflow: "hidden",
  },
  cardHeader: {
    padding: "24px 24px 0",
    textAlign: "center",
  },
  cardTitle: {
    fontSize: "24px",
    color: "black",
    marginBottom: "8px",
  },
  cardDescription: {
    color: "#6b7280",
  },
  cardContent: {
    padding: "24px",
  },
  googleButton: {
    width: "100%",
    padding: "12px 12px",
    backgroundColor: "#fff",
    border: "1px solid #d1d5db",
    borderRadius: "8px",
    color: "black",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "12px",
    fontSize: "16px",
    transition: "all 0.3s",
    marginBottom: "24px",
  },
  separator: {
    position: "relative",
    margin: "24px 0",
    textAlign: "center",
  },
  separatorLine: {
    height: "1px",
    backgroundColor: "#e5e7eb",
    width: "100%",
  },
  separatorText: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    backgroundColor: "white",
    padding: "0 8px",
    fontSize: "12px",
    textTransform: "uppercase",
    color: "#6b7280",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  inputGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  label: {
    color: "black",
    fontWeight: "500",
    fontSize: "14px",
  },
  inputContainer: {
    position: "relative",
  },
  input: {
    width: "100%",
    padding: "12px 12px",
    border: "1px solid #d1d5db",
    borderRadius: "8px",
    fontSize: "16px",
    outline: "none",
    background: "#fff",
    color: "#222",
    transition: "border-color 0.3s",
  },
  passwordToggle: {
    position: "absolute",
    right: "12px",
    top: "50%",
    transform: "translateY(-50%)",
    background: "none",
    border: "none",
    color: "#9ca3af",
    cursor: "pointer",
    padding: "4px",
  },
  rememberRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  checkbox: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  forgotLink: {
    fontSize: "14px",
    color: "#50bc72",
    textDecoration: "none",
  },
  errorBox: {
    padding: "12px",
    borderRadius: "8px",
    backgroundColor: "#fef2f2",
    border: "1px solid #fecaca",
  },
  errorText: {
    fontSize: "14px",
    color: "#dc2626",
  },
  submitButton: {
    width: "100%",
    padding: "12px 12px",
    background: "linear-gradient(135deg, #50bc72, #41599c)",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.3s",
  },
  toggleText: {
    textAlign: "center",
  },
  toggleButton: {
    background: "none",
    border: "none",
    color: "#50bc72",
    fontWeight: "600",
    cursor: "pointer",
    textDecoration: "underline",
  },
  termsText: {
    fontSize: "12px",
    color: "#6b7280",
    textAlign: "center",
    lineHeight: "1.5",
  },
  termsLink: {
    color: "#50bc72",
    textDecoration: "none",
  },
  footer: {
    backgroundColor: "#0b1220",
    color: "white",
    padding: "48px 0",
  },
  footerContainer: {
    maxWidth: "1280px",
    margin: "0 auto",
    padding: "0 16px",
  },
  footerGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))",
    gap: "32px",
  },
  footerSection: {
    display: "flex",
    flexDirection: "column",
  },
  footerLogo: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginBottom: "16px",
  },
  footerLogoIcon: {
    width: "24px",
    height: "24px",
    background: "linear-gradient(135deg, #50bc72, #41599c)",
    borderRadius: "6px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "white",
    fontWeight: "bold",
    fontSize: "14px",
  },
  footerLogoText: {
    fontSize: "20px",
    fontWeight: "bold",
  },
  footerDescription: {
    color: "#9ca3af",
    lineHeight: "1.6",
  },
  footerTitle: {
    fontWeight: "600",
    marginBottom: "16px",
    color: "white",
  },
  footerList: {
    listStyle: "none",
    padding: 0,
    margin: 0,
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  footerLink: {
    color: "#9ca3af",
    textDecoration: "none",
    transition: "color 0.3s",
  },
  footerBottom: {
    borderTop: "1px solid rgba(255,255,255,0.06)",
    marginTop: "32px",
    paddingTop: "32px",
    textAlign: "center",
    color: "#9ca3af",
  },
  gradientBrand: {
    background: "linear-gradient(to right, #50bc72, #41599c)",
  },
  gradientText: {
    background: "linear-gradient(to right, #50bc72, #41599c)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    backgroundClip: "text",
  },
  button: {
    padding: "12px 24px",
    borderRadius: "8px",
    border: "none",
    cursor: "pointer",
    fontSize: "16px",
    fontWeight: "600",
    textDecoration: "none",
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    transition: "all 0.3s ease",
  },
  buttonPrimary: {
    background: "linear-gradient(to right, #50bc72, #41599c)",
    color: "white",
  },
  buttonSecondary: {
    background: "transparent",
    color: "#000",
    border: "2px solid #000",
  },
  buttonWhite: {
    background: "white",
    color: "#000",
  },
  floatingNavbar: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 100,
    background: "rgba(255, 255, 255, 0.1)",
    backdropFilter: "blur(20px)",
    border: "1px solid rgba(255, 255, 255, 0.2)",
    borderRadius: "24px",
    boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.25)",
  },
};

export default styles;
